import React, { useState, useEffect } from 'react';
import { MarketReport } from '../types';
import { FileText, Download, TrendingUp } from 'lucide-react';
import { getMarketFlash } from '../services/geminiService';

const MOCK_REPORTS: MarketReport[] = [
    { id: 'R1', title: 'Weekly Market Update - Wk 42', date: 'Oct 20, 2023', summary: 'Transition period for Leafy Greens. Berry market tightening.', url: '#', category: 'Weekly' },
    { id: 'R2', title: 'Tropicals Alert: Hurricane Impact', date: 'Oct 15, 2023', summary: 'Shipping delays expected from Gulf ports.', url: '#', category: 'Special Alert' },
    { id: 'R3', title: 'Weekly Market Update - Wk 41', date: 'Oct 13, 2023', summary: 'Potato harvest yields looking strong.', url: '#', category: 'Weekly' },
    { id: 'R4', title: 'Citrus Season Outlook 2024', date: 'Oct 01, 2023', summary: 'Detailed analysis of domestic citrus crop forecast.', url: '#', category: 'Special Alert' },
];

const FieldFlash: React.FC = () => {
  const [summary, setSummary] = useState<string>('Analyzing market data...');
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const fetchSummary = async () => {
        const text = await getMarketFlash();
        setSummary(text);
        setLoading(false);
    };
    fetchSummary();
  }, []);

  return (
    <div className="p-8 bg-white min-h-full overflow-y-auto">
      <div className="max-w-5xl mx-auto">
        <div className="flex items-center gap-3 mb-8">
          <div className="p-3 bg-red-100 rounded-full text-red-600">
            <TrendingUp size={24} />
          </div>
          <div>
             <h1 className="text-2xl font-bold text-gray-900">Field Flash</h1>
             <p className="text-gray-500">Market intelligence and crop reports.</p>
          </div>
        </div>

        {/* AI Executive Summary */}
        <div className="bg-white rounded-xl shadow-md border-l-4 border-[#004B87] p-6 mb-10">
            <h2 className="text-lg font-bold text-gray-800 mb-3 flex items-center gap-2">
                <span className="relative flex h-3 w-3">
                  <span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-blue-400 opacity-75"></span>
                  <span className="relative inline-flex rounded-full h-3 w-3 bg-[#004B87]"></span>
                </span>
                Live Market Summary
            </h2>
            <div className={`text-gray-700 leading-relaxed ${loading ? 'animate-pulse' : ''}`}>
                {summary}
            </div>
            {!loading && (
                <p className="text-xs text-gray-400 mt-4 text-right">Generated by Gemini based on real-time desk inputs.</p>
            )}
        </div>

        {/* Report Archive */}
        <h3 className="text-lg font-bold text-gray-800 mb-4">Archived Reports</h3>
        <div className="space-y-4">
            {MOCK_REPORTS.map(report => (
                <div key={report.id} className="bg-white rounded-lg p-5 border border-gray-200 shadow-sm flex flex-col sm:flex-row justify-between items-start sm:items-center hover:border-blue-300 transition-colors">
                    <div className="flex items-start gap-4">
                        <div className={`p-3 rounded-lg ${report.category === 'Special Alert' ? 'bg-orange-50 text-[#F37021]' : 'bg-blue-50 text-[#004B87]'}`}>
                            <FileText size={24} />
                        </div>
                        <div>
                            <h4 className="font-bold text-gray-900">{report.title}</h4>
                            <p className="text-sm text-gray-500 mb-1">{report.date} • <span className="font-medium">{report.category}</span></p>
                            <p className="text-sm text-gray-600">{report.summary}</p>
                        </div>
                    </div>
                    <button className="mt-4 sm:mt-0 px-4 py-2 bg-gray-100 text-gray-700 rounded-lg hover:bg-gray-200 text-sm font-medium flex items-center gap-2 transition-colors">
                        <Download size={16} /> Download
                    </button>
                </div>
            ))}
        </div>

      </div>
    </div>
  );
};

export default FieldFlash;